name: Nuget release

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+-alpha**'
    - '[0-9]+.[0-9]+.[0-9]+-beta**'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Pack VelcroPhysics
      run: dotnet pack -c LinuxRelease src/VelcroPhysics.All.sln -o Temp
    - name: Upload to nuget
      run: dotnet nuget push --skip-duplicate -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json Temp/*